
<div id="qrcode-box">

    <div id="qrcode-image">
<!--        <img src="img/face.png" style="width: 270px;height:270px;" />-->
    </div>

    <div class="bottom-status">
        <span class="status-default">使用傻瓜 App 扫描二维码登录</span>
        <span class="status-scanned"  style="display: none;">扫描成功 请在手机点击确认</span>
    </div>

    <a id="qrcode-refresh" href="javascript:void(0);" style="display: none;">
        <span>二维码失效</span>
        <span>请点击刷新</span>
    </a>

</div>

<br>

<div class="app-mock">
    <button id="btn-scan">扫描二维码</button>
    <button id="btn-confirm" disabled>确定登录</button>
    <button id="btn-cancel">取消登录</button>
</div>

<hr>

<div id="info">
    <div id="info-qrcode"></div>
    <div id="info-check"><p></p></div>
</div>


<script>
    $(function() {

        var uuid = '';

        function fresh_qrcode() {
            $.get('/qrcode/get', function(response1) {
                var data1 = response1.data;
                uuid = data1.uuid;

                // Render qrcode
                $('#qrcode-image').qrcode({
                    width: 270,
                    height: 270,
                    text: data1.qrcode
                });

                $('#info-qrcode').html('Response: ' + JSON.stringify(data1));
                $('#info-check').html('');

                // Check the qrcode status
                var i = 0;
                var checkInterval = setInterval(function() {
                    $.get('/qrcode/check', {'uuid': data1.uuid}, function(response2) {
                        var data2 = response2.data;

                        // Check info
                        $('#info-check').html('Loop: ' + ++i + ' --- ' + JSON.stringify(data2));

                        if (data2.state == 0) { // 正常状态

                        } else if (data2.state == 1) { // 已扫描
                            $('#qrcode-image').html('<img src='+ data2.user_face +' style="width: 270px; height: 270px;" />');
                            $('.bottom-status .status-default').hide();
                            $('.bottom-status .status-scanned').show();
                        } else if (data2.state == 2) { // 已确认登录
                            clearInterval(checkInterval);
                            $('.bottom-status .status-scanned').html('登录成功');

                            // 调用使用 uuid 进行登录的接口，以便生成保持登录状态所需的 Cookie
                            $.get(data2.login_url, function(response3) {
                                if(!response3.success) {
                                    alert(response3.message);
                                    return false;
                                }

                                setTimeout(function() {
                                    window.location.href = '/';
                                }, 500);
                            });
                        } else if (data2.state == -1 || data2.state == -2) { // 已过期或已取消
                            $('#qrcode-refresh').show();
                            $('.bottom-status .status-default').show();
                            $('.bottom-status .status-scanned').hide();
                            clearInterval(checkInterval);
                        }
                    });
                }, 1000);
            });
        }

        // Init qrcode
        fresh_qrcode();

        $('#qrcode-refresh').click(function() {
            $('#qrcode-image').html('');
            $('#qrcode-refresh').hide();
            $('#btn-confirm').prop('disabled', true);
            fresh_qrcode();
        });

        // 模拟手机端扫描二维码
        $('#btn-scan').click(function() {
            $.get('/qrcode/scan?uuid=' + uuid, function(data) {
                console.log(data);
                $('#btn-confirm').prop('disabled', false);
            });
        });

        // 模拟手机端确认登录
        $('#btn-confirm').click(function() {
            $.get('/qrcode/confirm?uuid=' + uuid, function(data) {
                console.log(data);
            });
        });

        // 模拟手机端取消登录
        $('#btn-cancel').click(function() {
            $.get('/qrcode/cancel?uuid=' + uuid, function(data) {
                console.log(data);
            });
        });
    });

</script>