
<div id="login-box">
    <div id="qrcode">
        <div id="qrcode-image"></div>
        <a id="qrcode-refresh" href="javascript:void(0);" style="display: none;">
            <span>二维码失效</span>
            <span>请点击刷新</span>
        </a>
    </div>

    <div class="bottom-status">
        <span class="status-default">使用115组织 App扫描二维码登录</span>
        <span  class="status-scanned" style="display: none;">扫描成功 请在手机点击确认</span>
    </div>
</div>


<div id="info">
    <br>
    <div id="info-qrcode"></div>
    <div id="info-check"></div>
</div>



<script>
    $(function() {

        $.get('/qrcode/get', function(response1) {
            var data1 = response1.data;

            // Render qrcode
            $('#qrcode-image').qrcode({
                width: 270,
                height: 270,
                text: data1.qrcode
            });

            $('#info-qrcode').html(JSON.stringify(data1));

            // Check the qrcode status
            var i = 0;
            var checkInterval = setInterval(function() {
                $.get('/qrcode/check', {'uuid': data1.uuid}, function(response2) {
                    var data2 = response2.data;

                    if (data2.state == 0) {
                        // 正常状态
                    } else if (data2.state == 1) {

                    } else if (data2.state == -1 || data2.state == -2) {
                        $('#qrcode-refresh').show();
                        clearInterval(checkInterval);
                    }
                });
            }, 5000);

        });


    });

</script>