<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>QR Code Demo</title>

        <link href="/css/style.css" rel="stylesheet" type="text/css" />

        <!-- jquery -->
        <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.js"></script>

        <!-- https://github.com/jeromeetienne/jquery-qrcode -->
        <script src="/js/jquery-qrcode/jquery.qrcode.js"></script>
        <script src="/js/jquery-qrcode/qrcode.js"></script>
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>

    </body>
</html>
